#!/bin/sh

. gconfig

TUSER=${DISTRO:-ubuntu}

usage() {
  echo "Usage: ${0##*/} [OPTION]... <command>"
  echo "Run command on build target."
  echo
  cat << EOF
  --help		display this help and exit
  --user|-u <username>	run as <username> instead of ubuntu
  --env|-e "NAME=VALUE ..."	modify the environment
EOF
}

if [ $# != 0 ] ; then
  while true ; do
    case "$1" in
      --help|-h)
        usage
        exit 0
        ;;
      --user|-u)
        TUSER="$2"
        shift 2
        ;;
      --env|-e)
        ENV="$2"
        shift 2
        ;;
      --*)
        echo "unrecognized option $1"
        exit 1
        ;;
      *)
        break
        ;;
    esac
  done
fi

#if [ $# = 0 ] ; then
#  usage
#  exit 1
#fi

docker exec -u $TUSER -i gitian-target $*
